### ISSUE TITLE
Odoo crashes after dropping a database

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/rest-framework#108]
It might happen that a database is deleted, expecially while developing new features.
If module `base_rest` is installed in at least one DB (even the deleted one), the `get_request` override in `base_rest/http.py` will eventually try to initialize the deleted database without checking if it still exists. So when the `odoo.registry(db)` line is reached, Odoo tries to initialize a Registry for a non existing database, and it crashes.

PRs:

- [ ] 11.0: #109
- [x] 12.0: #110
- [x] 13.0: #111
- [x] 14.0: #112

**Comment by lmignon** [comment]
Thank you. Merged in versions where travis is not :red_circle:
