### ISSUE TITLE
Support for authentication

### ISSUE THREAD

**Issue by warp10** [OCA/rest-framework#12]
Unless I overshot snippets of code in base_rest, it looks like the module does not allow to authenticate to private services in a RESTful way. I guess most of the APIs written with this framework will only be available to authenticated users, so it would be great to add support for authentication with a standard request shared among services.

By the way, how do you manage authentication with the current module? An RPC call to login and get the session?

**Comment by lmignon** [comment]
Hi @warp10 
The authentication to use for services developed on top of base_rest must be specified into the controller with the key `_default_auth` https://github.com/OCA/rest-framework/blob/11.0/base_rest_demo/controllers/main.py#L10
Therefore you can use any authentication mechanism developed for odoo controllers. This kink of authentication mechanism is easy to develop. For our internal use in a **private** network we've developed an authentication mechanism based on a token provided into the http headers https://github.com/akretion/odoo-shopinvader/tree/10.0/auth_api_key

If you want to authenticate as a a user, you must initialize an http session by calling the login method in xmlrpc..

```python
import requests

# create a session
sess = requests.session()

# login into odoo
data = {"jsonrpc": "2.0", "method": "call", "params": {"db":"odoo-base_rest_product","login":"admin","password":"admin"}}
sess.post('http://localhost:8069/web/session/authenticate', json=data)

# use this session to call your services (in this case I've a product service implementing search withour required params)
res = sess.get('http://localhost:8069/rest_api/private/product/search')
print(res.json())

```

**Comment by warp10** [comment]
Hi @lmignon 

Fair enough. It's definitely easy to implement and quite transparent for the API's user. BTW, how about adding this piece of information to the documentation? I can take care of that if you think it might be a nice addition.

PS: Congrats for this great module. I was lucky enough to attend your talk at Odoo Experience and find out about this thing, it's helping me a lot!

**Comment by lmignon** [comment]
@warp10 Thank you for your positive feedback! 

>  BTW, how about adding this piece of information to the documentation? I can take care of that if you think it might be a nice addition.

Indeed, this could be useful for everyone and there is never enough documentation. I would be happy to review and integrate any contributions, whether technical or documentation. Thanks in advance!

**Comment by warp10** [comment]
@lmignon Just sent PR #13 for that. Not sure if a CLA is needed for this kind of contribution, nevertheless my company (that is: Openforce) signed an entity CLA, so I should be covered by that already. Let me know if there is any issue with the PR, I'll try and fix it.

**Comment by lmignon** [comment]
@warp10 Thank you!

**Comment by ychirino** [comment]
There are two problems I see with this approach:
- That would not work for a Bearer Token implementation which conveys both, the access key and the database to connect to.
- A client who is not accustomed to retain the notion of a session would (most clients probably aren't) would, if I were to fix this at the rest service implementation, create a new session per API request.

To fix this, it looks like this module shall provide custom implementations for:

- `Root.setup_session` - deviate altogether if coming from a rest endpoint which doe not enforce a session header.
- `Root.setup_db` - deviate on `Bearer-Token` header

What do you think?

**Comment by ychirino** [comment]
Just a neat calculation, on continuous load of 1000 req/sec that would end up with 604.9000.000 sessions created (assuming 7 days TTL)

**Comment by lmignon** [comment]
@ychirino The module can use any kind of authentcation mechanism implemented by Odoo. The  authentication method to use can be specified into the controller with the key  `_default_auth` https://github.com/OCA/rest-framework/blob/11.0/base_rest_demo/controllers/main.py#L10

Here it's for example an addon used to put in place an authentication method based on an api key provided into the header (to use in private networks) https://github.com/OCA/server-auth/pull/56

**Comment by ychirino** [comment]
@lmignon So if I understand the linked module right, it works around the exposed issue through [this line](https://github.com/OCA/server-auth/pull/56/files#diff-fa0a8fde24d5f4bbef5918fbe4ca4d16R17). Is that correct?

Looking at the whole flow in the module again, it seems that a session is created on every request, still. Am I missing something?

**Comment by bnisevic** [comment]
Hi! Thanks for your support to the community!

Can you give us more info how we can have headers in Swagger interface. I use custom auth service with customised ir.http, but I also transfer a JWT in a header, and there are no headers form in Swagger.

**Comment by lmignon** [comment]
@bnisevic You just need to override `_get_openapi_default_parameters`the into you service implementation

```python
    def _get_openapi_default_parameters(self):
        defaults = super(
            BaseShopinvaderService, self
        )._get_openapi_default_parameters()
        defaults.append(
            {
                "name": "API-KEY",
                "in": "header",
                "description": "Ath API key",
                "required": True,
                "schema": {"type": "string"},
                "style": "simple",
            }
        )
        defaults.append(
            {
                "name": "PARTNER-EMAIL",
                "in": "header",
                "description": "Logged partner email",
                "required": False,
                "schema": {"type": "string"},
                "style": "simple",
            }
        )
return defaults
```

**Comment by bnisevic** [comment]
Thanks. I managed to use this and get the field on the Swagger form but Swagger doesn't put the header. It doesn't come to my server and it isn't displayed in the example cURL.
![Screenshot_2019-05-13 Odoo](https://user-images.githubusercontent.com/1433428/57622383-c48e2800-758d-11e9-91d3-84f5e751f574.png)

**Comment by lmignon** [comment]
@bnisevic  For me it works on every projects where we use it...
![image](https://user-images.githubusercontent.com/544090/57680352-b4c62080-762d-11e9-8e83-ef9e686eb7c4.png)

**Comment by bnisevic** [comment]
OK. Thanks for your help! When I get more time I will try to debug this. Until then I will just use Postman.

**Comment by neobht** [comment]
If "Authorization" param in header it does not work correct.
If else another then it work correct.

**Comment by neobht** [comment]
May be to add features to authorization in swagger-ui:
`openapi: 3.0.0
...

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only

security:
  - bearerAuth: []`

**Comment by neobht** [comment]
You just need to override to_openapi  into you service implementation for Bearer and API-Key Auth:
```python
    def to_openapi(self):
        root = super(AuthenticationService, self).to_openapi()
        root.update(
            {
                "components":
                    {
                        "securitySchemes": {
                            "BearerAuth": {
                                "type": "http",
                                "scheme": "bearer",
                                "bearerFormat": "JWT"
                            },
                            "ApiKeyAuth": {
                                "type": "apiKey",
                                "in": "header",
                                "name": "api_key",
                            }
                        }
                    },
                "security": [{
                    "BearerAuth": [],
                    "ApiKeyAuth": []
                }]
            })
        return root
```

**Comment by iledarn** [comment]
Shouldn't there be statelessness for true rest  API? https://restfulapi.net/statelessness/
(basic authentication)
