### ISSUE TITLE
Restapi method not working

### ISSUE THREAD

**Issue by Master-Y0da** [OCA/rest-framework#123]
I try to use the suggest of use decorators on service methods, like this:

`

    @restapi.method([("/delete","DELETE")])
      def delete_user(self):
        return {"success": True}`

But is'nt working...when I look into swagger all my endpoints have POST method, no matter if I try with get, post ,put, delete, always creates them with POST method.

**Comment by lmignon** [comment]
@lvar The decorator is not right... It should look like
```python
    @restapi.method([(["/delete], "DELETE")])
    def delete(self):
        return {"success": True}
```

**Comment by lmignon** [comment]
@lvar feels free to reopen the issue is my proposal doesn't work.

**Comment by Master-Y0da** [comment]
@lmignon  still not working...this only works if you change the function name to "delete"...so what is the idea of having the decorator if swagger detects the http method based on the name of the function ? ...not working with a custom name, like this:

`

    @restapi.method([(["/delete"], "DELETE")])
    def delete_user(self, message):
        return {'response': 'Get called with message ' + message}`

**Comment by lmignon** [comment]
@lvar It's strange. This new api is wroking in a lot of places. :thinking:

**Comment by Master-Y0da** [comment]
@lmignon  ou!! I'm using version 13.0.2.0.1 ...maybe this is fixed in current version, sorry.
