### ISSUE TITLE
[14.0] base_rest: Create endpoint function won't work on website form submit POST

### ISSUE THREAD

**Issue by jose-pcg** [OCA/rest-framework#124]
**Issue summary**:

Can't get `create()` endpoint working on website form submit POST

Version: 14.0 (not tested on previous versions)

**Current behaviour**:
I have a **create** function like this:

```
from odoo.addons.component.core import Component

class PartnerPublicService(Component):
    _inherit = "base.rest.service"
    _name = "partner.service"
    _usage = "partners"
    _collection = "custom.public.services"  # collection class added on another file
    _description = """
        Random description
    """
    
    def create(self, **params):
        partner = self.env["res.partner"].create({"name": params["name"], "vat": params["vat"]})
        return {"message": "Partner successfully created with ID %s" % partner.id}

    def _validator_create(self):
        return {"name": {"type": "string", "required": True}, "vat": {"type": "string", "required": False}}
```

I tried to send a POST request to it from outside Odoo and it **works great** but when try on a website form `params` **came empty**.

**Expected behaviour**:

`create()` endpoint works well on both outside POST and website form submit POST requests.

**Additional info**:

Website form submit POST works when uninstalling **base_rest** and its dependency (**component**) and using a common Odoo controller endpoint.

**Comment by etobella** [comment]
I think you are missing the decorator

**Comment by jose-pcg** [comment]
Hi @etobella 

Can you give an example, please?

**Comment by etobella** [comment]
```python
    @restapi.method(
        [(["/create"], "POST")],
        input_param=restapi.CerberusValidator(
            {"name": {"type": "string", "required": True}, "vat": {"type": "string", "required": False}}
        ),
        output_param=restapi.CerberusValidator(
            {"message": {"type": "string", "required": True}}
        ),
        auth="user",
    )
```

you might need to add
```python
import logging
from odoo.addons.base_rest import restapi
```

I think the validator_create does not have any more sense.

**Comment by jose-pcg** [comment]
@etobella thank you!

I just tried and got an even more weird behavior. 

The endpoint got unavailable when adding the decorator and its params. I got a 404.

If I remove the decorator the endpoint gets available once again, but only from outside Odoo (I'm using Postman).

Is there anything else I'm missing in my code?

**Comment by etobella** [comment]
change the ["/create"] for ["/"] and try again, I changed the endpoint on my comment.

Also, I don't know if you need a put or a post

If you use my code, the new endpoint was "..../create" and the method was POST.

**Comment by lmignon** [comment]
@jlopezg The call to the api must POST a json document.
