### ISSUE TITLE
Can't install it on Odoo 14

### ISSUE THREAD

**Issue by caalvinz** [OCA/rest-framework#127]
Hi dear,

Could you give me a hand for this?
I tried to install the branch 14 on Odoo 14. While installing it on the Apps, it popped up an error.

![image](https://user-images.githubusercontent.com/4986240/110575639-335a4f00-812d-11eb-8424-78fef57ae781.png)

**Comment by etobella** [comment]
You are missing the connector repository from OCA

**Comment by caalvinz** [comment]
> You are missing the connector repository from OCA

Thanks a lot.
I tried to install [OCR connector](https://github.com/OCA/connector)  by following the steps on [this page](https://odoo-community.org/blog/the-oca-blog-1/post/how-to-install-oca-modules-79).

After the step 4. Update the addons list in your database (Menu `Apps > Update Apps List` in developer mode)
I couldn't see any module on the apps page.

![image](https://user-images.githubusercontent.com/4986240/110711823-29d4f380-81ce-11eb-8e5e-4a3b7ff59f13.png)

**Comment by caalvinz** [comment]
I got it.

Here are the steps:
```
git clone https://github.com/OCA/connector.git
cd connector
pip3 install -r requirements.txt
```
and then start odoo with this new folder as part ot the addons-path, such as
```
python3 odoo-bin --addons-path="addons,../custom-addons/connector" -d odoo
```

**Comment by sbidoul** [comment]
Looks like this is resolved.
