### ISSUE TITLE
datamodels default value have no effect 

### ISSUE THREAD

**Issue by lingjiawen** [OCA/rest-framework#129]
Hi, I try to write default value in datamodels like this:   
![image](https://user-images.githubusercontent.com/26227995/111245519-ba348d80-863f-11eb-80a1-2c6d79779b0d.png)   
And i used in services like this:
![image](https://user-images.githubusercontent.com/26227995/111245709-067fcd80-8640-11eb-96c7-87016ebfb6ab.png)   
The values(spu_search_param) i printed like normal. But when i print limit/offset/order, it's None.
![image](https://user-images.githubusercontent.com/26227995/111245763-1ac3ca80-8640-11eb-8f4d-16bddc90c391.png)   
I try to give a breakpoint for it.
![image](https://user-images.githubusercontent.com/26227995/111246066-99b90300-8640-11eb-9153-0fa59a060727.png)
This is what confused me. Do you have any suggestions for me? Thank you so much!

**Comment by a87b01c14** [comment]
> Hi, I try to write default value in datamodels like this:
> ![image](https://user-images.githubusercontent.com/26227995/111245519-ba348d80-863f-11eb-80a1-2c6d79779b0d.png)
> And i used in services like this:
> ![image](https://user-images.githubusercontent.com/26227995/111245709-067fcd80-8640-11eb-96c7-87016ebfb6ab.png)
> The values(spu_search_param) i printed like normal. But when i print limit/offset/order, it's None.
> ![image](https://user-images.githubusercontent.com/26227995/111245763-1ac3ca80-8640-11eb-8f4d-16bddc90c391.png)
> I try to give a breakpoint for it.
> ![image](https://user-images.githubusercontent.com/26227995/111246066-99b90300-8640-11eb-9153-0fa59a060727.png)
> This is what confused me. Do you have any suggestions for me? Thank you so much!

**use " missing=10 " replace "default=10"**

**Comment by ajepe** [comment]
@lingjiawen loading default that way will not work
```python
    latitude = fields.Float(required=False, allow_none=False, load_default=90.0001011)
    longitude = fields.Float(required=False, allow_none=False, load_default=80.0001013)
```
make use of __load_default__ as shown above.
