### ISSUE TITLE
strategies to avoid conflicting datamodel names ?

### ISSUE THREAD

**Issue by kevinkhao** [OCA/rest-framework#138]
Hi,

We have just a few modules using this and already we came across name conflicts. 

Datamodel names like "sale.order" and "sale.order.line" make sense to me when I'm writing a module. It makes so much sense that I forget that other modules are very likely to do the same. It seems likely that this will occur if there are many public modules using base_rest_datamodel.

Have you found a good strategy or convention to avoid this ? When I had the problem I just prefixed the datamodel names with the module name.

**Comment by rvalyi** [comment]
Hello I hit the same issue (because I had the base_rest_demo installed) and I have the very same concern if we want this module to be popular in the OCA...
