### ISSUE TITLE
Documentation not clear for odoo.addons.component.core dependency source

### ISSUE THREAD

**Issue by sylnsr** [OCA/rest-framework#15]
I'm using Odoo v 10

This module is breaking my deployment because it can find odoo.addons.component.core  

I have the https://github.com/OCA/connector module (according to oca_requirements.txt) and from that project, I installed `cachetools>=2.0.1,<3.0.0`

What provides odoo.addons.component.core.AbstractComponent ?

Trace from fresh install:
```2018-11-05 21:21:31,735 43 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1325, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1346, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/mnt/extra-addons/base_rest/__init__.py", line 2, in <module>
    from . import components
  File "/mnt/extra-addons/base_rest/components/__init__.py", line 1, in <module>
    from . import service
  File "/mnt/extra-addons/base_rest/components/service.py", line 11, in <module>
    from odoo.addons.component.core import AbstractComponent
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 60, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
ImportError: No module named component
```

**Comment by sylnsr** [comment]
OK, I see in the https://github.com/OCA/connector repo, it provides a list of available addons in that repo, namely:  
- component
- component_event
- connector
- connector_base_product

I can't find documentation for the details of how the oca_requirements.txt file is supposed to be used/understood .. so if the oca_requirements.txt file in this _this_ project lists [`connector`](https://github.com/OCA/rest-framework/blob/10.0/oca_dependencies.txt) then are we to understand that it means every available addon in the https://github.com/OCA/connector *repo* should be installed or just the connector *addon* from that repo ?

**Comment by sylnsr** [comment]
I went ahead and installed every available addon (except for the test addons of course) from the https://github.com/OCA/connector repo, (not sure if installing them _all_ is necessary..)  but now its complaining for RetryableJobError from odoo.addons.queue_job.exception which [is not provided by the connector repo](https://github.com/OCA/connector/search?l=Python&q=RetryableJobError)

So where can we get that from and should it be added to the documentation for this module, or am I missing some understanding of the current documentation here?

**Comment by sylnsr** [comment]
It appears that this class _used to be_ supplied by the connector repo, [however pull 211 removed it](https://github.com/OCA/connector/pull/211/files#diff-3659697a1392b1bca095f424149ea69dL55) from exception.py

**Comment by sylnsr** [comment]
So from checking the manifest I found that one of the dependencies is https://github.com/OCA/queue which has an addon named `queue_job` which provides RetryableJobError and adding _just_ the `queue_job` addon from that repo is enough to close the loop.

So instead of checking the manifests for the various projects down the dependency rabbit-hole, could we just indicated in the docs which addons are needed from which repos?  It think it will make adoption simpler for sure.

**Comment by guewen** [comment]
You shouldn't need `connector`, only `component`, and then you don't need `queue_job` neither which is a dependency of `connector`. Why do you need to manually check the manifests? The dependencies are automatically installed, you should not need to install them manually (as long as you have cloned the repos and added them to the addons path).

**Comment by sylnsr** [comment]
OK, then perhaps I don't understand why it is that in [oca_requirements.txt, it lists `connector`](https://github.com/OCA/rest-framework/blob/11.0/oca_dependencies.txt) .. maybe that's only for runbot ?   But even then it sounds like even component would be needed so I would expect that to be listed in that file as a required addon?  Maybe that's the main red-herring. Not sure.

Regarding "as long as you have cloned the repos" .. could you elaborate on the scope of  "the repos" .. do you mean all the OCA repos?  I check the manifest to get a clue about which repo to clone since my use case as the devops guy negates (or at least questions) cloning them all.

**Comment by lmignon** [comment]
@sylnsr The oca_requirements is a way for oca tools used to run tests on travis to know which others oca repositories are required to get the sources of dependencies specified into the __manifest__ file of the addons into the current repository.  (https://github.com/OCA/maintainer-quality-tools/blob/master/README.md)
It's indeed sometimes hard to know where to find the dependencies of a specific addon. On our side, we use pip to install our addons so all the dependencies are automatically installed at the same time. 

With pip, the installation of odoo with base_rest and all the dependencies can be done in 5 commands.... 
```
virtualenv venv
. venv/bin/activate
pip install -r https://raw.githubusercontent.com/odoo/odoo/10.0/requirements.txt
pip install https://nightly.odoo.com/10.0/nightly/src/odoo_10.0.latest.zip
pip install --pre odoo10-addon-base-rest
```

There are others ways to install odoo and oca addons, the best one is the one you are the most comfortable with... 

https://odoo-community.org/blog/the-oca-blog-1/post/how-to-install-oca-modules-79

**Comment by sylnsr** [comment]
Ah, I wasn't aware of the pip install option for OCA addons.  A valuable tip indeed.  Thanks for that.  For Odoo, we install via the deb package.

**Comment by sylnsr** [comment]
Will use pip install option and assume that for any/every OCA addon going forward.  It seems devops engineers are expected to learn this somewhere along the way as I just did, so closing issue.
