### ISSUE TITLE
Can't import Datamodel

### ISSUE THREAD

**Issue by Master-Y0da** [OCA/rest-framework#156]
I'm getting exception error `name 'ModelMeta' is not defined`
When I try to import Datamodel class -> `from odoo.addons.datamodel.core import Datamodel`

Any suggestion ? Thanks for the help.

**Comment by etobella** [comment]
Did you install the requirements?

**Comment by Master-Y0da** [comment]
@etobella The only package I can't install is marshmallow-objects , because is giving to me compatibility errors with another package. This error is because of this ?

**Comment by etobella** [comment]
Probably
