### ISSUE TITLE
Licensing of datamodel modules

### ISSUE THREAD

**Issue by davejames** [OCA/rest-framework#164]
The rest of the modules in the rest-framework repo are all licensed under LGPL since https://github.com/OCA/rest-framework/pull/28 with the exception of the `datamodel` and `base_rest_datamodel` which remain licensed under AGPL.

Is there any possibility to relicense these modules for the same rationale as https://github.com/OCA/rest-framework/pull/28? I am happy to open a PR if there is no objection.

**Comment by davejames** [comment]
Sorry for the tag, but @lmignon would you mind considering this? I think you're the author of these modules as well as the re-licensing PR I quoted.

**Comment by lmignon** [comment]
@davejames It's OK for me relicence to LGPL. Feel free to make a PR in this way...

**Comment by davejames** [comment]
Thanks @lmignon, I have created PRs for 12.0, 13.0 and 14.0

**Comment by simahawk** [comment]
all merged
