### ISSUE TITLE
generic rest endpoints

### ISSUE THREAD

**Issue by mrkazoodle** [OCA/rest-framework#165]
Hi,

I've come across a comment in this project that it would be possible to make a module that would provide generic rest endpoints. The reason to choose not to was to avoid exposing too much of odoo's internals and to limit the number of points of integration.

There is already a generic webservice: xmlrpc. There is little support for this exotic kind of service: this is a disadvantage of odoo.

There are modules available, for example https://github.com/itpp-labs/sync-addons 

In order to maintain an overview of rest endpoints that are in use you could implement logging.

This would help to increase the popularity of your project, the potential help from the community, and (based on your large number of contributions) maybe this could make it into core odoo? We don't need more software projects, instead we actually need less and better maintained software.

So may I please ask to reconsider?

**Comment by fdegrave** [comment]
I'm currently working on something close to a clone of ModelSerializer from Django Rest Framework extending the Datamodel from base_rest_datamodel. It's not a full generic REST API as it requires each endpoint to be declared explicitly, but it removes a large part of the verbosity for creating one. Depending on my needs and the time I can put in it, I could possibly push things up to the automated creation of CRUD endpoints for each model (and the possibility to execute public methods as well).

**Comment by fdegrave** [comment]
There is my first pull request on the matter: https://github.com/OCA/rest-framework/pull/177
