### ISSUE TITLE
Example of tests for datamodel

### ISSUE THREAD

**Issue by Plaoo** [OCA/rest-framework#172]
Hi, I created a rest api using datamodels, I would like to ask you to share an example of tests. Among the sources of the repo I don't find anything that can help me, external documentation is welcome.

**Comment by fdegrave** [comment]
Maybe this: https://github.com/OCA/rest-framework/blob/cba68741ba5863471b186ea36305c10fed8d474b/base_rest_demo/tests/test_new_api.py
