### ISSUE TITLE
Trouble with input params when Datamodel contains list

### ISSUE THREAD

**Issue by gdgellatly** [OCA/rest-framework#173]
Hi,

I'm probably doing something wrong but given (through Swagger UI)

`curl -X GET "http://localhost:14069/job/search?states=confirmed&states=progress" -H "accept: application/json"`

![image](https://user-images.githubusercontent.com/5093264/123723533-ab1bd780-d8de-11eb-9f93-38823a03b908.png)

with a service signature of

```python
@restapi.method(
        [(["/", "/search"], "GET")],
        input_param=Datamodel("job.search"),
        output_param=Datamodel("job", is_list=True),
        auth="public",
    )
```
 and a Datamodel definition for states of

```python
states = fields.List(fields.String)
```
EDIT: Results in `odoo.exceptions.UserError: BadRequest {'states': ['Not a valid list.']}`

No matter what the input params are always just converted to a dict of `{'states': 'progress'}`. Basically standard python dict behaviour taking last argument.

Now I can kind of work around for states, but equally I want to accept a list of ids which is a bit more problematic.  Any ideas?

**Comment by gdgellatly** [comment]
I found that Marshmallow by default sets explode=True in the schema. I overrode this to convert to False and then I get comma delimited inputs from swagger. But then the parser can't handle it as it just sees it as a string with some commas in it so not sure that is right way either.

**Comment by Mraimou** [comment]
I had the same issue, but it works from a REST client
