### ISSUE TITLE
Do we need _default_cors on RestController ?

### ISSUE THREAD

**Issue by sbidoul** [OCA/rest-framework#175]
We have `_default_auth` already, which is invaluable to apply the same authentication method to a whole set of services.

When calling services from a browser app served from another domain than Odoo we have to configure CORS.
Does it make sens to configure the `cors` route option at the controller level so it can also apply to a collection of services ?

**Comment by lmignon** [comment]
IMO, yes it make sens to also allow to configure the `cors` route option at controller level

**Comment by sbidoul** [comment]
Done in #174 and friends.
