### ISSUE TITLE
base_rest: Architecture (r) evolution: Use python types to describe and process methods

### ISSUE THREAD

**Issue by lmignon** [OCA/rest-framework#216]
After a deep analysis of the [fastapi ](https://fastapi.tiangolo.com/) library, I'm convinced that we could apply the same concept to base_rest to describe our methods and provide the right documentation. In the same time, we could also use the same convention and syntax to handle methods with  path / query and body parameters.

**Comment by simahawk** [comment]
Do you mean relying only on typing for validators? That would be great!

**Comment by lmignon** [comment]
@simahawk Yes...
