### ISSUE TITLE
Can't generate swagger document

### ISSUE THREAD

**Issue by bnisevic** [OCA/rest-framework#23]
Hi! Thanks for this great piece of code!

I was building on top of your base_rest_demo addon. But I can't find a way to generate Swagger API definitions automatically. I tried to c&p and edit .json file in data folder but that didn't work. Here is what I get in Swagger:
![screenshot_2019-01-25 odoo](https://user-images.githubusercontent.com/1433428/51716970-53a71c80-203f-11e9-9f05-f79f304c7cc1.png)

If you can put somewhere in the docs how this can be generated that will be awesome!

**Comment by lmignon** [comment]
Hi @bnisevic. The schema is generated from the python code. Therefore, there is no json file to provide into the data folder.  You can find some information on how to develop your own services into the module description https://github.com/OCA/rest-framework/tree/11.0/base_rest#usage. 
The development process is also explained into  [Odoo Experience 2018 presentation](https://www.youtube.com/watch?v=kWlniXgM3Sc&index=8&list=PLgRkpfC5FsCzEid-KcHTorEymPNO8QeyI) and [slides](https://docs.google.com/presentation/d/e/2PACX-1vStBIMdVI8JeUL7Ac8GlplPlbLnE3ybcrrhzqxVhjFQa-wzU2BSvBUxqAq9vl9CLxqFYctmk7_ysUDZ/pub?start=true&loop=true&delayms=3000) 
Finally, the [demo module](https://github.com/OCA/rest-framework/tree/11.0/base_rest_demo) is also a good starting point to understand how to develop your own services.

**Comment by bnisevic** [comment]
Hi @lmignon! Thanks for your reply!

My question is about this particular process:
> The schema is generated from the python code.

How do you generate this? How do you run it to generate API definition JSON file? I can't find that on the https://github.com/OCA/rest-framework/tree/11.0/base_rest#usage. I found some methods for doing this on Swagger site, but my question is how did you generate those for base_rest_demo. I would like to use the same method. Is there a python program for doing that? Or you did it with something else?
If you put that in reply I can make PR for documentation.

**Comment by farzeni** [comment]
Hello @bnisevic,
I had the same problem. What @lmignon intended is that schemas used by swagger are generated by the python code under controllers/ directory in base_rest module (it is not something you have to run).

You should define in your service class all validators methods for your requests. So if you define 

```
def create(self, **data):
   """
   This comment will become summary of methods in swagger docs
   """
   return  do_something()
```

you should also write validators for relative requests and responses

```
# validator for input data
def _validator_create():
   retun {
       'whatever': {'type':string},
       [...]
  }

# validator for output data
def _validator_return_create():
   retun {
       'id': {'type': 'integer'},
       'whatever': {'type':'string'},
       [...]
  }


```

If you do not define one of the _validator methods above, the api-doc controller will raise a 500 error (which is the one you are probably experiencing).

Here my question for @lmignon, wouldn't be possible to modifiy these methods in service.py

```
    def _get_input_schema(self, method_name):
        validator_method = '_validator_%s' % method_name
        if not hasattr(self, validator_method):
            return None
        return getattr(self, validator_method)()

    def _get_output_schema(self, method_name):
        validator_method = '_validator_return_%s' % method_name
        if not hasattr(self, validator_method):
            return None
        return getattr(self, validator_method)()
```

To return an empty dict instead of None? This would allow swagger to generate the basic doc without such error.

(last but not least, thank you for this addon it was a game changer for us!)

**Comment by bnisevic** [comment]
Thanks a lot @farzeni ! I will try to do that and see. Thanks!

**Comment by lmignon** [comment]
@farzeni 

> To return an empty dict instead of None? This would allow swagger to generate the basic doc without such error.

Feel free to propose this change...  IMO, we must keep the current implementation for the methods `_get_input/ouput_schema` but change the code here https://github.com/OCA/rest-framework/blob/11.0/base_rest/components/service.py#L298 with

```python
input_schema = self._get_input_schema(name) or {}
output_schema = self._get_output_schema(name) or {}
```

**Comment by bnisevic** [comment]
@farzeni it works even if I use only return validator (e.g. _validator_return_get():). Thanks again! I wouldn't be able to resolve this without your input.
