### ISSUE TITLE
Customizing ID description

### ISSUE THREAD

**Issue by bnisevic** [OCA/rest-framework#25]
Hello good people of OCA!

A new question araised  for which I couldn't find answer. Is there an easy way to customize this value here https://github.com/OCA/rest-framework/blob/11.0/base_rest/components/service.py#L292

Whenever we use ID it will always say Item id, but I have some special cases where customizing this description would be suitable.

Thanks for help!

**Comment by lmignon** [comment]
@bnisevic The only way is to override the method `_get_openapi_paths` into your service implementation, inspect the result and modify the description associated to the id.

**Comment by bnisevic** [comment]
Thanks for the explanation!

**Comment by bnisevic** [comment]
Hi again!

Maybe better question for this issue would be: How to use custom parameters for get requests? For example if I don't want to use id nor name, but some other string? How I can define that without overriding BaseRestService methods?

**Comment by bnisevic** [comment]
If I get it right, it's enough to use it as parameter like in demo module for name:
def search(self, name):

**Comment by bnisevic** [comment]
No, obviously that doesn't work for get method, whatever I use except _id I get no parameters in path.
![Screenshot_2019-03-20 Odoo](https://user-images.githubusercontent.com/1433428/54699170-d248a380-4b30-11e9-8521-f9b1d7f874b1.png)

**Comment by lmignon** [comment]
@bnisevic By convention, only two methods are callable by "HTTP GET" call.
* `/my_service/{id}` -> will call the methode `def get(self, _id):`" https://github.com/OCA/rest-framework/blob/11.0/base_rest_demo/services/partner_services.py#L19 (used to get information of a specific record)
* `/my_service` -> will call the method `def search(self, **params):`  https://github.com/OCA/rest-framework/blob/11.0/base_rest_demo/services/partner_services.py#L25 (used to search for information)

If you want to add additional query paramters, you must implement validator methods. These methods must return a [Cerberus schema](http://docs.python-cerberus.org/en/stable/) do define the expected schema.

For exemple if you want to add a parameter to get information of a specific instance `/my_service/{id}.my_params=xyz` you must provide the method: 
```python
def _validator_get(self):
        return {
            'my_params': {
                'type': 'string',
                'nullable': False,
                'required': True,
                },
}
```
The method `get` should look like: `def get(self, _id, my_params=None)`

The same apply if you want to get information without specifying a specific id (search) `/my_service?my_params=xyz`

```python
def _validator_search(self):
        return {
            'my_params': {
                'type': 'string',
                'nullable': False,
                'required': True,
                },
}
```
https://github.com/OCA/rest-framework/blob/11.0/base_rest_demo/services/partner_services.py#L93
The method `search` should look like: `def search(self, my_params=None)`

The provided schema is used to validate the parameters and filter out unknown parameters before calling the implementation. It's also used to document the services.

**Comment by bnisevic** [comment]
Thank you very much for the extensive explanation! It clarifies much. I figured out that this is not flexible enough as I hoped for. I know that in Odoo all IDs are int. But in my usecase I'm integrating external services with Odoo. And for ID we use UUID across whole system of which Odoo is tiny part. 

So for that purpose it would be ideal if I can make `def get(self, _id, my_params=None)` work without _id, for which obviously there is no easy way.

I'm trying to override `_get_openapi_paths` and I have `partner/{foo_id}?foo_id=b1e2ca06-b258-4825-9753-b15a5a622831` in Swagger. But for response I get `405 Method Not Allowed`.

I tried to search where 405 is defined, but couldn't find it. It is not in `_get_openapi_default_responses` nor in `_get_openapi_paths`. Do you know why I get 405 on this?

**Comment by bnisevic** [comment]
And one more question, if I use `def get(self, _id, my_params=None)` that still means that _id is required?

**Comment by bnisevic** [comment]
And one more. Sorry. :)
Can I defined another endpoint like "search"? E.g. "seek".

**Comment by bnisevic** [comment]
I manage to make a new endpoint:

```
    def customer(self, foo_id):
        return self._to_json(self._get(foo_id=foo_id))

    def _validator_customer(self):
        return {
            'foo_id': {
                'type': 'string',
                'nullable': False,
                'required': True,
            },
        }

    def _validator_return_customer(self):
        return self._validator_return_get()
```

This will be POST request by default, and when I changed `_get_openapi_paths` in the following part partner/customer endpoint became GET.

```
.....
        if name in ('search', 'get', 'customer'):
.....
                if name == 'get':
                    paths.setdefault('/{id}', {}).update(get)
                    paths['/{id}/get'] = get
                if name == 'search':
                    paths['/'] = get
                    paths['/search'] = get
                if name == 'customer':
                    paths['/'] = get
                    paths['/customer'] = get
.....
```
But again I get 405 Method Not Allowed.

**Comment by lmignon** [comment]
@bnisevic 
base_rest defaine default routes by default into your controller... https://github.com/OCA/rest-framework/blob/11.0/base_rest/controllers/main.py#L51

Http GET are forwarded by default to `get`and `search`. This rule is put in place to avoid that a method designed to update data from being called by an HTTP GET. 

You are free to add your own routes into the controller to allow HTTP GET calls to an other endpoint/method.  Nevertheless, the documentation will not be properly generated for this endpoint. I've some ideas on how to improve the addon for such a case but not the resource/time to implement these idea https://github.com/OCA/rest-framework/issues/6

You should also take a look at gaphql https://github.com/OCA/rest-framework/tree/12.0/graphql_base
It's an other way to expose you business logic in a simple flexible and efficient way. https://www.youtube.com/watch?v=qplioZuxARc

**Comment by bnisevic** [comment]
@lmignon thanks for the explanation! And do you know how this 405 Method Not Allowed is generated? I'm having trouble to find that.

**Comment by bnisevic** [comment]
If I understood correctly I get 405 because RestController doesn't create route for my method allowed for GET it does it only for POST:

```
@route([
    ROOT_PATH + '<string:_service_name>',
    ROOT_PATH + '<string:_service_name>/search',
    ROOT_PATH + '<string:_service_name>/<int:_id>',
    ROOT_PATH + '<string:_service_name>/<int:_id>/get'
], methods=['GET'], auth="user", csrf=False)
def get(self, _service_name, _id=None, **params):
    method_name = 'get' if _id else 'search'
    return self._process_method(_service_name, method_name, _id, params)

@route([
    ROOT_PATH + '<string:_service_name>',
    ROOT_PATH + '<string:_service_name>/<string:method_name>',
    ROOT_PATH + '<string:_service_name>/<int:_id>',
    ROOT_PATH + '<string:_service_name>/<int:_id>/<string:method_name>'
], methods=['POST'], auth="user", csrf=False)
def modify(self, _service_name, _id=None, method_name=None, **params):
    if not method_name:
        method_name = 'update' if _id else 'create'
    if method_name == 'get':
        _logger.error("HTTP POST with method name 'get' is not allowed. "
                      "(service name: %s)", _service_name)
        raise BadRequest()
    return self._process_method(_service_name, method_name, _id, params)

@route([
    ROOT_PATH + '<string:_service_name>/<int:_id>',
], methods=['PUT'], auth="user", csrf=False)
def update(self, _service_name, _id, **params):
    return self._process_method(_service_name, 'update', _id, params)

@route([
    ROOT_PATH + '<string:_service_name>/<int:_id>',
], methods=['DELETE'], auth="user", csrf=False)
def delete(self, _service_name, _id):
    return self._process_method(_service_name, 'delete', _id)
```

**Comment by lmignon** [comment]
> If I understood correctly I get 405 because RestController doesn't create route for my method allowed for GET it does it only for POST:

You're right

**Comment by bnisevic** [comment]
But can I just override `def get` in my controller? I'm trying to do that now, but having trouble to find these definitions in base controller.

**Comment by lmignon** [comment]
> But can I just override `def get` in my controller? I'm trying to do that now, but having trouble to find these definitions in base controller.

something like this....

```python
@route([
'/my_root/my_service/<char:my_char_id>'   
'/my_root/my_service/<char:my_char_id>/get'
], methods=['GET'], auth="user", csrf=False)
def my_get(self, my_char_id, **params):
    method_name = 'get'
    return self._process_method("my_service", "my_get", my_char_id, params)
```

**Comment by bnisevic** [comment]
I would propose in a PR following code change under this line https://github.com/OCA/rest-framework/blob/12.0/base_rest/controllers/main.py#L51

```
@route([
        '<string:_service_name>',
        '<string:_service_name>/<string:method_name>',
        '<string:_service_name>/search',
        '<string:_service_name>/<int:_id>',
        '<string:_service_name>/<int:_id>/get'
    ], methods=['GET'])
    def get(self, _service_name, _id=None, method_name=None, **params):
        if not method_name:
            method_name = 'get' if _id else 'search'

        if method_name == 'post':
            _logger.error("HTTP GET with method name 'post' is not allowed. (service name: %s)", _service_name)
            raise BadRequest()

        return self._process_method(_service_name, method_name, _id, params)
```

Does that sound acceptable for you? I think then we have more flexible get method?

**Comment by lmignon** [comment]
@bnisevic unfortunately, I don't think this change is a good idea. Indeed it would become possible to call any method via an HTTP GET even the methods modifying data. A basic principle from a design point of view is that no HTTP GET method should have the effect of modifying the system.

The only possibility I see is to develop a way to mark that a method is accessible via HTTP GET and check this constrains into the generic controller. (In this case the generic controller could be modified as proposed and the implementation should check the constrains)


```python
@restapi.method(method='GET')
def my_method(self, **params)
    pass
```

**Comment by bnisevic** [comment]
OK. I understand. Thanks for your help!
