### ISSUE TITLE
Base rest : allow return an http error (404, ...)

### ISSUE THREAD

**Issue by fmdl** [OCA/rest-framework#255]
With base_rest, it is not possible to return a specific error like 404, 201, ...

it is only return 500 by raise UserError

It is possible to manage the return error ?

**Comment by MatiasConTilde** [comment]
You can like this:
```python
from odoo.http import Response
from http import HTTPStatus

...

def get():
    return Response(status=HTTPStatus.NOT_FOUND)
```
