### ISSUE TITLE
'API-KEY' is missing in Access-Control-Allow-Headers list

### ISSUE THREAD

**Issue by krisachai** [OCA/rest-framework#256]
**Is your feature request related to a problem?**
I was trying to access base_rest controller with api_key authentication (via fetch) from a local vue app (browser) but there is no `API-KEY` in the `Access-Control-Allow-Headers` . Therefore, the request was denied by the browser.

**Describe the solution you'd like**
'API-KEY' got injected into Access-Control-Allow-Headers somehow.

**Describe alternatives you've considered**
My current workaround is to manually added the `API-KEY` in odoo/http.py 
```
    def dispatch(self):
        if self._is_cors_preflight(request.endpoint):
            headers = {
                'Access-Control-Max-Age': 60 * 60 * 24,
                'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization, API-KEY'
            }
            return Response(status=200, headers=headers)
```

Maybe I did something wrong ?

**Comment by nubeosupport** [comment]
Hello @krisachai , 
I have got the same problem as you and do the same workaround.

But in the response header of my POST method ( after that the preflight method was OK) , there is no more Access-Control-Allow-Origin in the header so it doesn't work.

Did you have the same issue? Do you solve it?

![image](https://user-images.githubusercontent.com/107417545/185426656-8aa26551-fe6f-4a41-9cbc-0872107fae7f.png)

![image](https://user-images.githubusercontent.com/107417545/185426606-214d1ce7-9d0c-412c-bb0b-41cc46f4f8c9.png)

Thanks.
