### ISSUE TITLE
[14.0] Multiple entry in requirements for apispec

### ISSUE THREAD

**Issue by GSLabIt** [OCA/rest-framework#257]
https://github.com/OCA/rest-framework/blob/1f67797f57e78655ef11323e03873024cbb99e16/requirements.txt#L2-L3

Which one should be taken in account?

we got here:

https://github.com/OCA/rest-framework/blob/6a3d7ac28d944a3ddbe92ece22549f330e5fb51b/base_rest_datamodel/__manifest__.py#L15

and here:

https://github.com/OCA/rest-framework/blob/6c2b87c4ccf50b6748d0244fdc889e98301e1ff6/base_rest_auth_jwt/__manifest__.py#L19

**Comment by lmignon** [comment]
@GSLabIt "apispec>=4.0.0" is the right one. It's already defined by base_rest. I would prefer to not specify a specific version into sub addons. 

Why do you say it's a bug?

**Comment by GSLabIt** [comment]
@lmignon `pip3 install -r requirements.txt` will find 2 entries and will not install packages

**Comment by HviorForgeFlow** [comment]
@GSLabIt have you tried to update python3-pip to last version and check if this error persist?

**Comment by GSLabIt** [comment]
@HviorForgeFlow It works thx
