### ISSUE TITLE
Canno't open swagger document (method not allowed)

### ISSUE THREAD

**Issue by haithem2019** [OCA/rest-framework#26]
Hello ,
I'am trying to create rest api using your module in odoo . 
when i put this url : (http://localhost:8079/rest_api/public/product )  doesn't work and show me method is not allowed (capture 1)
![capture1](https://user-images.githubusercontent.com/49242346/55487072-4ef57a80-5625-11e9-8a7e-1f89162350fa.png)

my code source is :

from odoo.addons.base_rest.controllers import main
class MyRestController(main.RestController):
    _collection_name = "base.rest.public.services"
    _root_path = '/rest_api/public'
    _default_auth = "public"

--------------------------------------------------------
class ProductService(Component):
    _inherit = 'base.rest.service'
    _name = 'product.service'
    _collection = 'paradon.rest.public.services'
    _usage = 'product'
    _description= """ Product Services """

    def get(self ,_id):
        """"
        Get product's informations
        """
        return self._to_json(self._get(_id))

    def _validator_get(self):

        return{}

    def _validator_return_get(self):
        res = {
            "id": {"type":"integer","required":True,"empty": False},
            "name": {"type": "string", "required": True, "empty": False},
            "price": {"type": "float", "required": True, "empty": False}

        }
        return res

----------------------------------------------
Which i had understand that i'am not allowed to use request GET so how can I use request POST . Is it possible to give me an example of post request and how to solve problem of method not allowed. Finally when i open this link  (http://localhost:8079/rest_api/public ) it should open the documentation swagger for my rest api is it truth ?

Thanks for helps.
Cordially Haitham

**Comment by bnisevic** [comment]
This is the link where you can see generated Swagger docs: http://127.0.0.1:8069/api-docs

And there you can send requests and also you can check cURLs there and test your requests accordingly outside Swagger.

How did you end up on port 8079?
