### ISSUE TITLE
Structural error when exporting and validating json in the online editor swagger

### ISSUE THREAD

**Issue by ychirino** [OCA/rest-framework#27]
The doc .json is generated correctly but when validating this in the online editor of swagger generates several structural errors of openapi. (Attached sample image), are you working on some correction of these structural errors or are you expecting some pull request to make these patches?

![Captura de pantalla de 2019-04-22 10-02-35](https://user-images.githubusercontent.com/37002368/56507506-1ee41d80-64e7-11e9-91b7-53569e1e120b.png)

**Comment by lmignon** [comment]
@ychirino PR to fix these errors are welcome.
