### ISSUE TITLE
How to write GET all method?

### ISSUE THREAD

**Issue by hminle** [OCA/rest-framework#33]
Hi,

How should I define a GET all partner method in base_rest_demo?

For example:

/partners --> GET all partners
/partners/{id} --> GET a specific partner

Thanks

**Comment by lmignon** [comment]
Hi,

You already have the two methods.... except taht the search requires a parameter "name"... 
Nevertheless you can modify the code to make it optional. https://github.com/OCA/rest-framework/blob/12.0/base_rest_demo/services/partner_services.py#L93

http://3375157-12-0-ad264e.runbot1-2.odoo-community.org/api-docs#/default/get_

**Comment by hminle** [comment]
@lmignon Hi, so it means that, I will make the id parameter optional, and then if clients call get method without id, I will return all partners, is that your point?

**Comment by lmignon** [comment]
@hminle You have to make the *name* parameter optional... for the search method. see https://github.com/OCA/rest-framework/blob/12.0/base_rest_demo/services/partner_services.py#L93

**Comment by hminle** [comment]
Thank you sir, I understand now
