### ISSUE TITLE
How to use postman to check API?

### ISSUE THREAD

**Issue by hminle** [OCA/rest-framework#35]
Hi,

I wonder how I can use POSTMAN application to check the REST API for private services?

Could you guys guide me?
Thanks

**Comment by MichiEnclustra** [comment]
You can do this with Postman: https://learning.getpostman.com/docs/postman/sending_api_requests/graphql

**Comment by sbidoul** [comment]
Check out [auth_api_key](https://github.com/OCA/server-auth/tree/12.0/auth_api_key).
