### ISSUE TITLE
How to config swagger to call https in this module?

### ISSUE THREAD

**Issue by hminle** [OCA/rest-framework#36]
Hi,

How can I use "Try it out" page to send https request?
What should I do to config it in this module?

Thanks,

**Comment by adrewtran** [comment]
Hi @sbidoul and @lmignon . I have the same issue, did you guys have solution for this?

**Comment by dreispt** [comment]
On Settings > Technical > System Parameters, try setting the `web.base.url` to and URL using https.

**Comment by lmignon** [comment]
@dreispt You're right. Thank you for the response.
