### ISSUE TITLE
[16.0][fastapi] "FastAPI Endpoint Runner" access rights causes login error

### ISSUE THREAD

**Issue by moitabenfdz** [OCA/rest-framework#367]
## Module
fastapi

## Describe the bug
Having "FastAPI Endpoint Runner" access rights causes an 500 Internal Server Error when trying to login.

## To Reproduce
**Affected versions**: 16.0

1. With fastapi installed, give an user "FastAPI Endpoint Runner" access rights.
2. Try to log in with that user.

**Expected behavior**
You can log in without any problem.

**Additional context**
Tested in runboat

**Comment by drewes** [comment]
@moitabenfdz I get a similar error. Error is as follows:

`ValueError: <class 'NameError'>: "name 'authenticated_partner_id' is not defined" while evaluating
" ['|', ('user_id', '=', user.id), ('id', '=', authenticated_partner_id)]"
`

Have any joy fixing the issue?

**Comment by lmignon** [comment]
This issue should be fixed by https://github.com/OCA/rest-framework/pull/410
