### ISSUE TITLE
[16.0] fastapi odoo module name is the same as the python module

### ISSUE THREAD

**Issue by obayit** [OCA/rest-framework#400]
## Module
fastapi

## Describe the bug
The name of the odoo module is the same as the name of the python module fastapi.

Because of this, running odoo from the directory where the fastapi module exists, causes import error (this is common when naming a file or a directory with __init__.py the same name of an installed python module).

I hope that a note in the readme point this out to avoid confusion. Renaming the module is not an option, I think.

Can there be a check to warn about naming a module after one of its python dependencies?

## To Reproduce
Run odoo instance with current working directory containing the fastapi module. An import error should appear when trying to install the module from the apps menu.

Not applicable

**Expected behavior**
Not applicable

**Additional context**
Not applicable

**Comment by lmignon** [comment]
@obayit Thank you for the report. Indeed it's a common issue but not releated to this specific addon.  A PR improving the documentation as suggested would be welcome.
