### ISSUE TITLE
[17] License mismatch

### ISSUE THREAD

**Issue by mfalatec** [OCA/rest-framework#445]
There is a license mismatch inside the fastapi module in files:

https://github.com/OCA/rest-framework/blob/17.0/fastapi/schemas.py
https://github.com/OCA/rest-framework/blob/17.0/fastapi/error_handlers.py

The module and the rest of the files are licensed under LGPL-3 and the above 2 files are licensed under AGPL-3.
@lmignon could you please take a look at this issue?

**Comment by lmignon** [comment]
merged in #447
