### ISSUE TITLE
fastapi_auth_jwt is merged without review in manifest the version still 16.0 in branch 17.0

### ISSUE THREAD

**Issue by kobros-tech** [OCA/rest-framework#480]
https://github.com/OCA/rest-framework/blob/17.0/fastapi_auth_jwt/__manifest__.py
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by sbidoul** [comment]
It also has installable=False. So it's just no's migrated yet.

**Comment by kobros-tech** [comment]
> It also has installable=False. So it's just no's migrated yet.

wow, is it really 😅

All right, now I have added my contribution to make it migrated fast.

by the way I am using jwt on top of it for version 17.0 so it means I tested, reviewed, and published to prod.
