### ISSUE TITLE
Unable to fetch record from postman

### ISSUE THREAD

**Issue by saikirubamj** [OCA/rest-framework#54]
Hi 

while use graphiql in browser its works.But while using in postman unable to fetch.
how to pass authorization token with requests if there is way where to fetch authorization token from this module

{
    "jsonrpc": "2.0",
    "id": null,
    "error": {
        "code": 100,
        "message": "Odoo Session Expired",
        "data": {
            "name": "odoo.http.SessionExpiredException",
            "debug": "Traceback (most recent call last):\n  File \"/home/ssd-01/Documents/Projects/school_bus/odoo/http.py\", line 619, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/ssd-01/Documents/Projects/school_bus/odoo/http.py\", line 309, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/ssd-01/Documents/Projects/school_bus/odoo/tools/pycompat.py\", line 14, in reraise\n    raise value\n  File \"/home/ssd-01/Documents/Projects/school_bus/addons/http_routing/models/ir_http.py\", line 443, in _dispatch\n    cls._authenticate(func.routing['auth'])\n  File \"/home/ssd-01/Documents/Projects/school_bus/odoo/addons/base/models/ir_http.py\", line 124, in _authenticate\n    getattr(cls, \"_auth_method_%s\" % auth_method)()\n  File \"/home/ssd-01/Documents/Projects/school_bus/odoo/addons/base/models/ir_http.py\", line 97, in _auth_method_user\n    raise http.SessionExpiredException(\"Session expired\")\nodoo.http.SessionExpiredException: Session expired\n",
            "message": "Session expired",
            "arguments": [
                "Session expired"
            ],
            "exception_type": "internal_error"
        }
    }
}

**Comment by sbidoul** [comment]
@saikirubamj  We usually use the graphql module in combination with [auth_api_key](https://github.com/OCA/server-auth/tree/12.0/auth_api_key).

**Comment by simahawk** [comment]
Use https://github.com/OCA/rest-framework/tree/14.0/base_rest_auth_api_key or https://github.com/OCA/rest-framework/tree/14.0/base_rest_auth_user_service
