### ISSUE TITLE
How to run graphiql

### ISSUE THREAD

**Issue by patmcb** [OCA/rest-framework#56]
Have installed modules locally and have Rest methods (search partner etc) all working OK in V12.0 but I have no idea how to get graphql working.

I am new to Odoo development.

Should the url be:
http://localhost:8069/graphql?
or maybe 
http://localhost:8069/graphql/demo

with say a post query like:
{
  Country(code: "BR", name: "Brazil" )
  {
    id
  }
}

A simple example for graphiql or Postman would be really appreciated.

**Comment by patmcb** [comment]
OK I managed to get working in Chrome graphiql extension but not with the windows graphiql.exe
For reference URL should be like:
 http://localhost:8069/graphql/demo?
and Query like:
{
  allPartners(companiesOnly: true) {
    name
    email
    country {
      name
      code
    }
  }
}

**Comment by patmcb** [comment]
The graphiql exe applications (linux or windows) have no session authentication as does the web browser extension which accounts for why these don't work - might be a way of logging in on the applications but I do not know how to do that.

**Comment by sbidoul** [comment]
@patmcb We usually use the graphql module in combination with [auth_api_key](https://github.com/OCA/server-auth/tree/12.0/auth_api_key). I don't know the exe application you mention so it may or may not work with it.

**Comment by WhiteTiger08** [comment]
I'm getting internal server error when trying to access 
http://localhost:8069/graphql/demo?

I debugged it and there is an error: "Must provide query string."

any help here?

**Comment by sbidoul** [comment]
Try http://localhost:8069/graph*i*ql/demo

**Comment by WhiteTiger08** [comment]
> Try http://localhost:8069/graph*i*ql/demo

Got it working, I was missing the "i". Thank you very much.

**Comment by WhiteTiger08** [comment]
The URL must be:

http://localhost:8069/graphiql/demo?
