### ISSUE TITLE
why the duplicate methods?

### ISSUE THREAD

**Issue by gurneyalex** [OCA/rest-framework#78]
I'm wondering why base_rest introduces duplicate endpoints.

* "GET /{id}", "GET /{id}/get" behave the same
* "GET /" and "GET /search" behave the same
* "POST /{id}/delete" and "DELETE /{id}" behave the same
* "POST /{id}/update" and "PUT /{id}" behave the same

There may be more. 

I find this confusing, and I think it clutters the interface without a good reason, and it makes interacting with these services more complicated than needed. IMO base_rest should only provide

* GET /{id}
* GET /
* DELETE /{id}
* PUT /{id}

Am I missing a design point?

**Comment by phuoctech** [comment]
The same question with you, I don't understand why?
