### ISSUE TITLE
Swagger UI accessible through REST API menuitem is broken

### ISSUE THREAD

**Issue by kevinkhao** [OCA/rest-framework#94]
Swagger UI seems broken as it is impossible to scroll.

![image](https://user-images.githubusercontent.com/19902174/104746145-2b92b580-574f-11eb-9e34-fa20659a2999.png)

**Comment by lmignon** [comment]
@kevinkhao Seems to be a bug only in odoo 14

**Comment by lmignon** [comment]
@kevinkhao fixed in fe848095b7e23567aa4d2b2030619ccfdb36256c
