### ISSUE TITLE
How to test endpoints with data

### ISSUE THREAD

**Issue by llabusch93** [OCA/rest-framework#95]
Dear contributors,

I am currently struggling with unit tests for my endpoints.

1. How can I do a `assertRaises(CustomExceptionType)` ? When I try to do so, it says that the exception was not raised, although it did (exception printed correctly in the logs). I assume that the test and the endpoint being tested, where the request it posted against, are running in two different threads, so any idea on this one?
2. When I set up test data in the unit test and try to test against those by posting references to those created data in a request to the endpoint, those data are not found. Again, different threads and different ORM environments. So we have two different database transactions, what results in not accessible test data...

Does anyone have a solution for my issue?

Thanks in advance!

**Comment by lmignon** [comment]
Hi @llabusch93 

To test your REST services you only need to test the logic implemented by your rest.service components. (You don't need to call the rest api).
For example if your services are registered under the collection "my.rest.services"..

```python

from odoo.addons.base_rest.controllers.main import _PseudoCollection
from odoo.addons.base_rest.tests.common import BaseRestCase
from odoo.addons.component.core import WorkContext

class PingServiceTest(BaseRestCase):
    @classmethod
    def setUpClass(cls):
        super(CommonCase, cls).setUpClass()
        collection = _PseudoCollection("my.rest.services", cls.env)
        cls.services_env = WorkContext(
            model_name="rest.service.registration", collection=collection
        )
    
    def test_create(self):
        ping_service = self.service_env.component(usage="ping")
        res = ping.create({})
        self.assertEqual(res, ...)
   ....
```
https://github.com/OCA/wms/tree/13.0/shopfloor/tests provides you a lot of examples on how you can tests your services

**Comment by llabusch93** [comment]
Thanks a lot, that's all I need @lmignon !

Would be great to maybe reference that in the documentation (a few more detailed examples), so it's clear from the beginning.

But that's another thing, this here is closed.

**Comment by lmignon** [comment]
@llabusch93 Feel free to make a PR to improve the documentation. Any help is greatly appreciated.

lmi
